<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-20T16:31:17 IST" name="Suite" finished-at="2025-05-20T16:31:32 IST" duration-ms="14989">
    <groups>
      <group name="Error">
        <method signature="ErrorValidationsTest.loginErrorValidation()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" name="loginErrorValidation" class="ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest"/>
      </group> <!-- Error -->
    </groups>
    <test started-at="2025-05-20T16:31:17 IST" name="Error Validations Test" finished-at="2025-05-20T16:31:32 IST" duration-ms="14989">
      <class name="ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:17 IST" name="launchApplication" finished-at="2025-05-20T16:31:23 IST" duration-ms="6553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:23 IST" name="loginErrorValidation" finished-at="2025-05-20T16:31:25 IST" duration-ms="1980" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect1 email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect1 email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:26 IST" name="tearDown" finished-at="2025-05-20T16:31:26 IST" duration-ms="509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:26 IST" name="launchApplication" finished-at="2025-05-20T16:31:28 IST" duration-ms="1564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:28 IST" name="productErrorValidation" finished-at="2025-05-20T16:31:31 IST" duration-ms="3335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest@56dc1551]" started-at="2025-05-20T16:31:31 IST" name="tearDown" finished-at="2025-05-20T16:31:32 IST" duration-ms="553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ECommerceapplication.E2EEcommerceApplication.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
  </suite> <!-- Suite -->
</testng-results>
